# Generated by Django 4.0 on 2021-12-26 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
        ('pos', '0002_rename_isactive_pos_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pos',
            options={'verbose_name': 'POS', 'verbose_name_plural': 'POS'},
        ),
        migrations.AlterField(
            model_name='pos',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
