# Generated by Django 4.0 on 2021-12-28 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_biometrics_auth_user_biometrics_enabled_and_more'),
        ('pos', '0004_alter_pos_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(max_length=255)),
                ('transaction_amount', models.CharField(max_length=255)),
                ('transaction_desc', models.CharField(max_length=255)),
                ('auth_type', models.CharField(max_length=255)),
                ('created_at', models.CharField(max_length=255)),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.pos')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='user.user')),
            ],
        ),
    ]
