# Generated by Django 4.0 on 2021-12-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_remove_transaction_user_transaction_consumer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='auth_type',
            field=models.CharField(choices=[('BIOMETRICS', 'biometrics'), ('RFID', 'rfid')], default='BIOMETRICS', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'in'), ('OUT', 'out')], default='OUT', max_length=255),
        ),
    ]
