# Generated by Django 4.0 on 2021-12-28 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_biometrics_auth_user_biometrics_enabled_and_more'),
        ('pos', '0007_alter_transaction_auth_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='consumer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consumer', to='user.user'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pos',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.pos'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='vendor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor', to='user.user'),
        ),
    ]
