# Generated by Django 4.0 on 2021-12-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_transaction_consumer_alter_transaction_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_title',
            field=models.CharField(default='Error!!!', max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_desc',
            field=models.TextField(),
        ),
    ]
