# Generated by Django 4.0 on 2021-12-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_alter_transaction_consumer_alter_transaction_pos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pos',
            name='token',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='pos',
            name='password',
            field=models.CharField(max_length=1024),
        ),
    ]
