# Generated by Django 3.2.5 on 2022-05-11 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0013_pos_token_alter_pos_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSHandovers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_made_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_type', models.CharField(choices=[('OBTAIN', 'obtain'), ('RETURN', 'return'), ('MAINTAIN', 'maintain'), ('SEIZE', 'seize')], default='OBTAIN', max_length=15)),
                ('request_approval', models.BooleanField(default=False)),
                ('collected_at', models.DateTimeField()),
                ('returned_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pos.pos')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requesting_vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
