# Generated by Django 3.2.5 on 2022-05-11 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0015_poshandovers_request_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshandovers',
            name='collected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='poshandovers',
            name='request_desc',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='poshandovers',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
