# Generated by Django 3.2.5 on 2022-05-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_auto_20220511_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reversed',
            field=models.BooleanField(default=False),
        ),
    ]
