# Generated by Django 3.2.5 on 2022-05-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_transaction_reversed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poshandovers',
            name='request_approval',
            field=models.CharField(choices=[('APPROVED', 'approved'), ('REJECTED', 'rejected'), ('PENDING', 'pending')], default='PENDING', max_length=15),
        ),
    ]
