# Generated by Django 4.0 on 2021-12-28 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biometrics_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='biometrics_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='biometrics_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rfid_auth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rfid_auth_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rfid_auth_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rfid_auth_pin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
