# Generated by Django 4.0 on 2021-12-29 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_biometrics_auth_user_biometrics_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rfid_auth_attempts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
