# Generated by Django 3.2.5 on 2022-03-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220320_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='atm_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
